apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-app
        app.kubernetes.io/name: node-app
    spec:
      containers:
      - name: node-app
        image: node-web-app:1.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080

        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10

        startupProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 10

