apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: 'formation-ns-dev'
  name: formation-deploy
spec:
  selector:
    matchLabels:
      app: my-webapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: nginx-app
        image: nginx:1.23.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
      - name: node-app
        image: node-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"