apiVersion: v1
kind: Pod
metadata:
    name: busybox
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /mysqlpassword
      name: mysql
  volumes:
  - name: mysql
    secret:
      secretName: mysql