apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - echo
      - "coucou"
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir: {}