apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
  - name: nginx-app
    image: nginx:1.23.2
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"